import { NextRequest, NextResponse } from 'next/server'
import { createServerSupabaseClient } from '@/lib/supabase-server'
import { z } from 'zod'

export const dynamic = 'force-dynamic'

const AUTO_PREFIXES = ['단계 변경:', '📇', '📅', '📁']

function isAutoGenerated(content: string | null, stageChangedTo: string | null): boolean {
  if (stageChangedTo) return true
  if (!content) return false
  return AUTO_PREFIXES.some(p => content.startsWith(p))
}

const updateSchema = z.object({
  type: z.enum(['전화', '문자', '이메일', '방문', '화상', '기타']).optional(),
  content: z.string().nullable().optional(),
  duration: z.number().nullable().optional(),
  occurred_at: z.string().optional(),
})

export async function PATCH(
  request: NextRequest,
  { params }: { params: Promise<{ id: string; iid: string }> }
) {
  try {
    const { id, iid } = await params
    const supabase = await createServerSupabaseClient()
    const { data: { session } } = await supabase.auth.getSession()
    if (!session) return NextResponse.json({ error: 'Unauthorized', success: false }, { status: 401 })

    // 소유권 확인
    const { data: existing } = await supabase
      .from('interactions')
      .select('content, stage_changed_to, user_id')
      .eq('id', iid)
      .eq('customer_id', id)
      .single()

    if (!existing) return NextResponse.json({ error: '이력을 찾을 수 없습니다', success: false }, { status: 404 })
    if (existing.user_id !== session.user.id) return NextResponse.json({ error: 'Unauthorized', success: false }, { status: 401 })
    if (isAutoGenerated(existing.content, existing.stage_changed_to)) {
      return NextResponse.json({ error: '자동 생성된 이력은 수정할 수 없습니다', success: false }, { status: 403 })
    }

    const body = await request.json()
    const parsed = updateSchema.safeParse(body)
    if (!parsed.success) return NextResponse.json({ error: parsed.error.flatten(), success: false }, { status: 400 })

    const { data, error } = await supabase
      .from('interactions')
      .update(parsed.data)
      .eq('id', iid)
      .eq('customer_id', id)
      .eq('user_id', session.user.id)
      .select()
      .single()
    if (error) throw error

    return NextResponse.json({ data, success: true })
  } catch (error: any) {
    return NextResponse.json({ error: error.message, success: false }, { status: 500 })
  }
}

export async function DELETE(
  request: NextRequest,
  { params }: { params: Promise<{ id: string; iid: string }> }
) {
  try {
    const { id, iid } = await params
    const supabase = await createServerSupabaseClient()
    const { data: { session } } = await supabase.auth.getSession()
    if (!session) return NextResponse.json({ error: 'Unauthorized', success: false }, { status: 401 })

    const { error } = await supabase
      .from('interactions')
      .delete()
      .eq('id', iid)
      .eq('customer_id', id)
      .eq('user_id', session.user.id)
    if (error) throw error
    return NextResponse.json({ success: true })
  } catch (error: any) {
    return NextResponse.json({ error: error.message, success: false }, { status: 500 })
  }
}
